### PR TITLE
Update Subscriptions Tutorial with one extra line

### PR DESCRIPTION
**Pull request by ivosequeros**
After following the subscriptions tutorial, I realised that there is a required line missing.

### CODE REVIEW

**Comment by bruce** [comment]
@ivosequeros Thanks! You're a keen reader!

Should the path be `/socket`, though?

**Comment by ivosequeros** [comment]
Hi Bruce!
I tried `/socket` but it was failing. By opening the Chrome Dev Tools, I saw that both Graphiql and Playground connect to `/websocket`, so I changed it and it worked.

screenshot 2018-09-20 at 00 56 20

**Comment by benwilson512** [comment]
@ivosequeros can you show how you have your socket setup? By default the path is `"/socket"` but if you've changed it in your Endpoint.ex that may be why.

**Comment by ivosequeros** [comment]
Sure. This is my Socket:
```
defmodule Server.UserSocket do
  use Phoenix.Socket
  use Absinthe.Phoenix.Socket, schema: Server.Schema

  transport :websocket, Phoenix.Transports.WebSocket

  def connect(%{"Authorization" => auth}, socket) do
    "Bearer " <> token = auth
    {:ok, resource} = Server.Authentication.Access.authenticate token
    socket = Absinthe.Phoenix.Socket.put_options socket, context: resource

    {:ok, socket}
  end

  def connect(_, socket) do
    {:error, :no_access}
  end

  def id(_socket), do: nil
end
```

And this is my Endpoint
```
defmodule Server.Endpoint do
  use Phoenix.Endpoint, otp_app: :lighthouse
  use Absinthe.Phoenix.Endpoint

  # The default was /socket, but it didn't work with Playground nor Graphiql.
  # It works with /websocket since Playground seems to connect any URL you give it + /websocket
  socket "/websocket", Server.UserSocket

  ...
end
```

**Comment by benwilson512** [comment]
Right, so the default is `socket "/socket", Server.UserSocket`. The issue you're having is that the GraphiQL interface will cache whatever preferences you have. If you change the `Endpoint` back to the default, clear your cache in GraphiQL, it'll go back to using that default.

**Comment by ivosequeros** [comment]
Hi @benwilson512, you're right. I cleaned the LocalStorage and it works with `/socket` 👍

**Pull request closed without merging**
