### PR TITLE
Failing test for empty query sdl render bug

### PR DESCRIPTION
**Pull request by kdawgwilk**
Example for #1105

### CODE REVIEW

**Comment by binaryseed** [comment]
I don't think this is a valid schema - the root query type can't be empty. What did you do to encounter the inspect failure?

**Comment by kdawgwilk** [comment]
Wouldn't the schema fail to compile in the tests if it was invalid?

**Comment by binaryseed** [comment]
http://spec.graphql.org/draft/#sec-Objects.Type-Validation

> An Object type must define one or more fields

It might be that Absinthe doesn't currently have a compile time validation for this part of the spec

**Comment by benwilson512** [comment]
@binaryseed I think this is related to that, but we may want to handle it a bit differently. There are certain schemas that are in valid in such a way where we can't meaningfully render them, but right now it tries to anyway if we `inspect`. We need some sort of fallback when inspecting because otherwise it is difficult to debug invalid schemas.

**Comment by kdawgwilk** [comment]
Resolved by #1167

**Pull request closed without merging**
