### PR TITLE
Allow maps as arguments in macros

### PR DESCRIPTION
**Pull request by kzlsakal**
This is one approach to possibly solve the issue https://github.com/absinthe-graphql/absinthe/issues/1225

My main goal is to support passing a map in the arguments for a directive that is wrapped in an `extend` macro.

### CODE REVIEW

**Review by maartenvanvliet — COMMENTED** [review]
Good catch! 

I think the best place to convert the AST to maps would be in the Schema.Notation module. This to prevent the AST from leaking into other parts of Absinthe.

We can limit support to literal maps only for now. This would most closely match the SDL notation.

Note that this issue also happens elsewhere: https://github.com/absinthe-graphql/absinthe/issues/1024

**Comment by kzlsakal** [comment]
Thanks for the feedback. I moved the logic to Notation as you both recommended.

**Review by benwilson512 — APPROVED** [review]
Looks great, thanks!

**Comment by hauleth** [comment]
When this will be released?

**Comment by hauleth** [comment]
This cause `Inspect.Error` to be written in generated SDL file while command happily succeeds.

**Comment by benwilson512** [comment]
Hey @hauleth please file an issue with the relevant info on this.

**Comment by hauleth** [comment]
I found more info - it works, but when the keys are binaries, not when keys are atoms. I will try to post more info when I will find time to spare.

**Comment by maartenvanvliet** [comment]
```
diff --git a/lib/absinthe/schema/notation/sdl_render.ex b/lib/absinthe/schema/notation/sdl_render.ex
index baac5a24..35ea517d 100644
--- a/lib/absinthe/schema/notation/sdl_render.ex
+++ b/lib/absinthe/schema/notation/sdl_render.ex
@@ -408,7 +408,7 @@ defmodule Absinthe.Schema.Notation.SDL.Render do
   end
 
   defp render_value(%Blueprint.Input.Field{name: name, input_value: value}),
-    do: concat([name, ": ", render_value(value)])
+    do: concat([to_string(name), ": ", render_value(value)])
 
   defp render_value(%{value: value}),
     do: to_string(value)
```
The `Inspect.concat/1` expects binaries so it fails here when it encounters an atom. Above patch fixes it but perhaps it's better to cast to a string or fail in the `expand_ast` call as pretty much anything can be the key of a map.

**Pull request merged**
