### PR TITLE
Use makeup_graphql to get GraphQL syntax highlighting in docs

### PR DESCRIPTION
**Pull request by Billzabob**
Docs before:
Screen Shot 2021-09-01 at 11 26 44 AM

Docs after:
Screen Shot 2021-09-01 at 11 26 04 AM

### CODE REVIEW

**Comment by benwilson512** [comment]
Very cool! What remains to take this beyond draft?

**Comment by Billzabob** [comment]
I'm using the master version of `ex_doc` in this because it doesn't work without the fix that @josevalim added [here](https://github.com/elixir-lang/ex_doc/commit/b25a0008f505258e42257d3c59af5ea7daaa5fae). So once there is a release for that I'll change this to actually use the latest version of `ex_doc` instead of using the `git` option and this will be good :)

**Comment by josevalim** [comment]
0.25.2 is out :)

**Comment by Billzabob** [comment]
This is good to go 👍

**Comment by benwilson512** [comment]
Thank you!

**Pull request merged**
