### PR TITLE
Added the ability to mutate the context variables inside root mutation resolvers

### PR DESCRIPTION
**Pull request by howleysv**
Added integration test to cover this behaviour, while validating that non-mutation resolvers are forbidden from attempting to mutate the context.

### CODE REVIEW

**Comment by bruce** [comment]
@howleysv Can you provide more detail on the motivation for this change?

**Comment by howleysv** [comment]
@bruce The use cases I'm thinking about is where you are storing authorization data inside the `context`, and your mutation necessitates an update to this state.

E.g.

- Logging in/out
- Mutation result means I now have access/lost access to resource X

**Comment by tlvenn** [comment]
Not sure I understand this @howleysv. The context lifecycle is a given request so at the end of your mutation, the context will be destroyed so what the point of trying to update it ?

**Comment by howleysv** [comment]
@tlvenn This new context would be available when resolving the **query** portion of the mutation response, after the mutation resolver completed successfully.

**Comment by benwilson512** [comment]
Right, the idea is that if you do something like:
```
mutation LogOut {
  logOut { someFieldWithAuthRequirements someOtherField}
}
```

`someOtherField` would return fine but `someFieldWithAuthRequirements` would not. This is OK for mutations; queries would not permit mutating the context. This is also supported by Sangria for example.

**Comment by tlvenn** [comment]
ha got it, thanks for the clarification both.

**Comment by bruce** [comment]
My main issue with this (and @benwilson512, we've talked about this sort of thing before): I don't like differently-sized tuples with the same atom "flag" -- it feels far too much like "magic arguments" for my taste. This is especially true with `{:ok, _, _this_right_here}` which has, in the past, been proposed for providing _errors_ in addition to a value. This is a sign, in my opinion, that we shouldn't differ the # of tuple members to indicate different behaviors.

Also: this feels a lot like resolution plugin territory.

**Comment by howleysv** [comment]
@bruce I'm open to implementing it differently, although I'm not sure the existing resolution plugin framework would facilitate updating the context.

**Comment by benwilson512** [comment]
Closing this in favor of doing this via middleware. Docs forthcoming.

**Pull request closed without merging**
