### PR TITLE
Proper Fragment Projection

### PR DESCRIPTION
**Pull request by benwilson512**
Note: there are test failures, but they're all related to complexity analysis at this point which needs to be more nuanced.

### CODE REVIEW

**Comment by benwilson512** [comment]
@howleysv hey btw are you able to try out this branch and see if it works with the scenarios you were running into previously?

**Comment by howleysv** [comment]
I can try run our integration test suite against it - we have a few custom things in our 1.2 fork that we need to port to 1.3 but I wouldn't expect too many failures related to them being absent...

I'll try look at it over the weekend, but next week will mostly be spent at Elixirconf :sunglasses:

**Comment by benwilson512** [comment]
Interesting, what did you fork for 1.2?

**Comment by howleysv** [comment]
Right now there's not a lot, we've been slowly removing our temporary features as they become possible in absinthe core and I think when this is merged we can probably move toward abandoning our fork.

We're currently using our fork to handle:
- correct merging of list of fragments (solved by this)
- updating context inside mutation resolvers (solvable with 1.3 middleware)
- some custom logging around diagnosing batch timeouts

**Comment by howleysv** [comment]
@benwilson512 looks good 👍
It seems to correctly resolve the insanely fragmented queries generated by our Relay (Classic) client

**Comment by benwilson512** [comment]
Excellent, glad to hear!

**Pull request merged**
