### PR TITLE
Fixes escape character sequences that are not on the last attributes

### LINKED ISSUE #588: Order of parsing with escapes returns errors depending on position in the query
### Environment

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0 (compiled with OTP 20)
absinthe 1.4.12 
absinthe_relay 1.4.3

Including a test on the master branch.

### Expected behavior

There is an example test for the master branch at https://github.com/BinaryNoggin/absinthe/commit/4573a9f460fe64df9021d54755b930e2c29107ef

I expect that the order of parsing with escape characters to parse no matter the position of the keys and values.

### Actual behavior

~~~elixir
 {:error,
             %Absinthe.Blueprint{
               adapter: nil,
               directives: [],
               errors: [],
               execution: %Absinthe.Blueprint.Execution{
                 acc: %{},
                 adapter: nil,
                 context: %{},
                 fields_cache: %{},
                 fragments: %{},
                 result: nil,
                 root_value: %{},
                 schema: nil,
                 validation_errors: [
                   %Absinthe.Phase.Error{
                     extra: %{},
                     locations: [%{column: 0, line: 1}],
                     message: "illegal: \") { name } }",
                     path: [],
                     phase: Absinthe.Phase.Parse
                   }
                 ]
               },
               flags: %{},
               fragments: [],
               input: "{ post(title: \"title\\\\\", body: \"body\") { name } }",
               name: nil,
               operations: [],
               result: %{},
               schema: nil,
               types: []
             }}
~~~

### Relevant Schema/Middleware Code

https://github.com/BinaryNoggin/absinthe/commit/4573a9f460fe64df9021d54755b930e2c29107ef

I created a test to show this happening.

### PR DESCRIPTION
**Pull request by adkron**
Fixes #588 

When running with attributes that have escape characters and
on the same line the order of the attributes matters for the outcome. If
the slashes appear in the last attribute, then everything parses
successfully. If the property appears earlier in the list, then an error
is returned instead.

The error:

~~~elixir
  validation_errors: [
    %Absinthe.Phase.Error{
      extra: %{},
      locations: [%{column: 0, line: 1}],
      message: "illegal: \") { name } }",
      path: [],
      phase: Absinthe.Phase.Parse
    }
  ]
~~~

This change allows the attributes to come in any order.

Amos King @adkron <amos@binarynoggin.com>

### CODE REVIEW

**Comment by metelik** [comment]
i like the solution :) i would embrace the '\' between '' in the message

**Comment by tapickell** [comment]
:+1: Good catch.

**Comment by benwilson512** [comment]
I believe this may be obviated by our move to NimbleParsec in 1.5, @bruce are you able to confirm that?

**Comment by bruce** [comment]
This tests fine on master; I'm going to merge. The lexer change will disappear with the lexer switch, but the tests will be handy.

**Comment by bruce** [comment]
Confirmed the switch to nimble_parsec fixes this issue as well; merged & tests pass in `master` and in #503.

Thanks for your work on this, @adkron; even though the fix was superseded, the tests are great to have around. Sorry for the delay in reviewing.

**Comment by adkron** [comment]
No problem. Thanks for taking care of it. 

Amos King
Binary Noggin

**Pull request merged**
