### PR TITLE
Fix complex default value InputType introspection

### LINKED ISSUE #490: Introspecting complex default values raises Protocol.UndefinedError
hi guys ~

i am using `default_value` in `input_object` ,  it *worked* , but there some error in console when i refresh the schema in graphql-playground ..

```elixir
input_object :article_filter do
    field(:first, :integer, default_value: 20)
    field(:order, :sort_order, default_value: :desc)
    field(:tag, :string, default_value: :all)
  end

field :posts, non_null(list_of(non_null(:post))) do
    arg(:filter, :article_filter, default_value: %{first: 20})
    resolve(&Resolvers.CMS.posts/3)
end
```

image

image

error detail:
```elixir
Request: POST /graphiql
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{first: 20}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Postgrex.Stream, Time, URI, Version, Version.Requirement

```

### PR DESCRIPTION
**Pull request by binaryseed**
WIP

This PR is an attempt to fix the bug that exists when introspecting a "complex" input value, ie: one that doesn't respond nicely to `to_string`...

closes #490

### CODE REVIEW

**Comment by binaryseed** [comment]
The code I have now does a hacky thing that gets close...

The problem is that I don't have a really solid way to turn the input `%{fancy_value: "qwerty"}` into the GraphQL representation: `{fancyValue: "qwerty"}`

**Comment by binaryseed** [comment]
I added a naive encoder to get the example test passing, but I don't think this is the right solution as-is

**Comment by binaryseed** [comment]
Any thoughts on this @bruce or @benwilson512 ?

**Comment by bruce** [comment]
I’ll give this a look this weekend. Thanks, @binaryseed!

**Comment by binaryseed** [comment]
I found a simple way to re-use most of the code that existed, just calling it recursively to render input objects!

There may be other cases like lists that I might need to check out

**Comment by steffenix** [comment]
Any progress on that?

**Comment by binaryseed** [comment]
I updated this, it was rendering all the things properly, so I validated that in a test & cleaned up the code.

At this point I suspect that master has moved quite far ahead into `1.5`, if we were to merge this would you make sure it wound up in the `1.4` branch @benwilson512 ?

**Comment by binaryseed** [comment]
Sweet, I used `adapter.to_external_name`.

Also I found the `unwrap:` option and used that explicitly so we can ensure that we properly handle any type of value inside a list...

@benwilson512 any other possible `Absinthe.Type.*` structs that I might need to handle?

**Comment by stef-otpyrc** [comment]
Is this for the next version?

**Comment by steffenix** [comment]
Is this for the next version?

**Comment by benwilson512** [comment]
This looks great, thank you!

**Pull request merged**
