### PR TITLE
Schema ensure query type

### PR DESCRIPTION
**Pull request by Logisig**
This is for #172, i think that this is the right way to do it. Need to update the other tests aswell. But would like some input before i start fixing them all.

### CODE REVIEW

**Comment by benwilson512** [comment]
This looks good to me, do you need any help getting the tests to pass?

**Comment by Logisig** [comment]
Thanks for looking at it, just needed to get some feedback before going through 27 tests. I am going to go through the rest and see if i can get them all to pass.

**Comment by bruce** [comment]
@Logisig Any update on this?

**Comment by Logisig** [comment]
Sorry for the late update, I fixed the last tests and now they all pass.

**Comment by benwilson512** [comment]
Gonna merge this into next.

**Pull request merged**
