### PR TITLE
SDL renders unwanted types

### PR DESCRIPTION
**Pull request by pyromaniac**
A failing test for #845

### CODE REVIEW

**Comment by benwilson512** [comment]
Merging into a bug fix branch, thanks!

**Comment by binaryseed** [comment]
This one looks like it's because we're generating the SDL based off of `Blueprint` structs, and not off of the result of `Absinthe.Schema.used_types` which walks through the `referenced_types`

I'm not sure of any clear way to bridge the gap and trim down the blueprint structs to just those used - `used_types` returns `Absinthe.Type` structs, not `Blueprint`

@benwilson512 Any ideas here?

**Comment by benwilson512** [comment]
@binaryseed I took a crack at implementing this earlier this week, it's a bit of a pain, basically we just have to reimplement the logic from `used_types`. On the upside, I think by doing it at the type definition stage we can actually mark the types as used or unused, and then `Absinthe.Schema.used_types` won't need to do any actual logic, it can just filter by `used`.

**Comment by binaryseed** [comment]
That would be pretty great actually, it'd probably improve the performance of the introspection queries for large schemas...

You have a branch up?

**Comment by benwilson512** [comment]
@binaryseed I'm working on it now, will push later today. Now that I'm thinking about it, do we even need to generate actual types for unused types? `import_fields` is run at the type def layer now, the actual object you're importing is completely irrelevant. It could be an issue if people were expecting to be able to look it up but there's just straight up better ways to do that in 1.5.

I think the ideal thing to do is mark the used type defs, and then at the Build phase only construct `Absinthe.Type` entities for those things that are actually used. `to_sdl` can filter on the `used` flag, and introspection stops needing to care about it at all.

**Comment by binaryseed** [comment]
Sounds like a good direction, I can say we've never needed the intermediate types and have only interacted with them when needing to ignore them

**Pull request merged**
