### PR TITLE
Serialize Default Values when Introspecting

### PR DESCRIPTION
**Pull request by benwilson512**
…when introspecting

### CODE REVIEW

**Comment by benwilson512** [comment]
@bruce this seems like the right call here. In theory we could specify default values in their client side form, but since the schema is internal I think server side form is much better, plus it means you can use stuff like `Timex.Date.now`. This requires serializing however when introspecting.

**Comment by bruce** [comment]
@benwilson512 Is this done or in-progress?

**Comment by benwilson512** [comment]
This is done, I just want you to look at it and see if it made sense.

**Comment by bruce** [comment]
:shipit: if all tests are green

**Pull request merged**
