### PR TITLE
WIP: supplemental PR related to dataloader PR

### PR DESCRIPTION
**Pull request by jfrolich**
see https://github.com/absinthe-graphql/dataloader/pull/21

### CODE REVIEW

**Comment by jfrolich** [comment]
Btw this is a small change, much of the changes are due to the code-formatter. How do I set the correct preferences?

**Comment by benwilson512** [comment]
@jfrolich the code base does not yet use the formatter, you'll want to ensure it isn't run on any PR you submit for the time being.

**Comment by jfrolich** [comment]
Understood, will clean it up later. After some experimentation I'm pretty pleased with a solution, almost done. Will add some examples later.

**Comment by binaryseed** [comment]
This PR is a bit stale, nearing 1 year since last touch. Closing for now..

**Comment by jfrolich** [comment]
That's fine. Any ideas or progress around fixing the underlying issue with dataloader (that dataloader is usable in contexts instead of only in the resolvers)? I was playing with an idea of trying to fix this using erlang processes instead of lazy data structures.

**Pull request closed without merging**
