### PR TITLE
don't pass introspection fields or objects to the def middleware callback

### LINKED ISSUE #565: Schema middleware callback affecting introspection
See https://github.com/absinthe-graphql/absinthe_plug/issues/159#issuecomment-399488012

### PR DESCRIPTION
**Pull request by benwilson512**
Fixes #565
Fixes https://github.com/absinthe-graphql/absinthe_plug/issues/159

### CODE REVIEW

**Comment by binaryseed** [comment]
What's the impact of this - presumably some APIs out there were installing middleware on these fields, right?

**Comment by benwilson512** [comment]
Probably not, they weren't available for this until one of the more recent 1.5 releases. I'll confirm that though.

**Comment by binaryseed** [comment]
Oh great, that’s fine with me then.

**Comment by binaryseed** [comment]
When does this expand function get called?

**Comment by benwilson512** [comment]
It gets called at compile time in the InlineFunctions phase. If the result of `expand` can be safely macro escaped then that field's compile time struct gets populated with the middleware list. If it can't be macro escaped, then it happens when the type is loaded at runtime.

**Comment by halostatue** [comment]
This should also close absinthe-graphql/absinthe_plug#159

**Pull request merged**
