### PR TITLE
fix: multiple pushes per client for subscriptions that have a context_id

### PR DESCRIPTION
**Pull request by girishramnani**
Dedups the Registry entries if they all have same topics and keys.

Fixes https://github.com/absinthe-graphql/absinthe/issues/1064

Note - This is not the best solution.

Explained the bug here https://github.com/absinthe-graphql/absinthe/issues/1064#issuecomment-1166711616

### CODE REVIEW

**Review by halfdan — APPROVED** [review]

**Comment by LetThereBeDwight** [comment]
Can we get this reviewed and brought in? We're using absinthe and would love to see it.

**Comment by girishramnani** [comment]
And I can fix any comments on this PR, have the bandwidth to do so.

**Comment by LetThereBeDwight** [comment]
Looks like @halfdan approved it prior to the test addition commit?

**Comment by girishramnani** [comment]
So can we ping @halfdan to approve again?

**Comment by benwilson512** [comment]
Halfdan is not part of this project so his approval is not particularly relevant here. I'll look at this now.

**Review by benwilson512 — CHANGES_REQUESTED** [review]
So if you comment out these lines:

```
      |> Enum.dedup_by(fn {topic, key_strategy, _} ->
        "#{topic}_#{:erlang.phash2(key_strategy)}"
      end)
```

And then run the tests, everything passes anyway, which means the tests aren't actually testing the code here.

Please write some tests that first _fail_ without the changes, and then show that the changes fix the test.

**Review by benwilson512 — CHANGES_REQUESTED** [review]
So if you comment out these lines:

```
      |> Enum.dedup_by(fn {topic, key_strategy, _} ->
        "#{topic}_#{:erlang.phash2(key_strategy)}"
      end)
```

And then run the tests, everything passes anyway, which means the tests aren't actually testing the code here.

Please write some tests that first _fail_ without the changes, and then show that the changes fix the test. You are welcome to reopen at that time.

**Pull request closed without merging**
